name:                lambda-chat-backend
version:             0.1.0.0
github:              "githubuser/lambda-chat-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/lambda-chat-backend#readme>

dependencies:
- base >= 4.7 && < 5
- websockets >= 0.12
- text
- regex-posix >= 0.95
- hspec >= 2.4
- QuickCheck >= 2.10

library:
  source-dirs: src

executables:
  lambda-chat-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chat-backend

tests:
  lambda-chat-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chat-backend
  lambda-chat-backend-quickcheck-test:
    main:                QuickSpec.hs
    source-dirs:         test-qc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chat-backend
